const ejs = require('ejs');
const fs = require('fs');
const path = require('path');
const graphql = require('graphql');

const ViewModel = require('./view_model/viewModel');
const scriptDir = __dirname;

module.exports = {
    /**
     * Builds an API page for a given schema
     * 
     * @param {graphql.GraphQLSchema} schema the schema as built by graphql.buildSchema (or buildClientSchema).
     * @param {string} apiName the name of the API. Will be displayed in page title and header.
     * @param {string} apiDescription a description of the API. Will be displayed in page header. 
     *                      May be HTML or Markdown (HTML will be sanitized).
     * @param {string} headPart a text that will be inserted at the end of the `head` tag in the output html. This can
     *                      be used to provide your own CSS (`link`/`style` tag), your own javascript code (`script` tag) or
     *                      anything else. Since this tag is inserted at the end of the `head` tag, it may override anything that
     *                      was generated by the tool. **This text will not be sanitized** as it is intended for use only by the script host,
     *                      so don't receive this as input from external users (or sanitize first).
     * @returns {Promise.<string>} a promise that represents the rendered HTML as a string.
     */
    buildAPIPage: function (schema, apiName, apiDescription, headPart){
    
        let templateParam = {
            viewModel: new ViewModel(schema, apiName, apiDescription, headPart),
        }
    
        let promise = new Promise((resolve, reject) => {
            ejs.renderFile(path.join(scriptDir,'templates/main.ejs'), templateParam,null,function(err,str){
                if (err){
                    reject("Could not render: " + err);
                    return;
                }
                resolve(str);
            });
        })
        return promise;
    }
    
}